In [ ]:
#
# Program 1: Calculate a determinant (6x6)
#
# Input: Matrix
# Output: The value of determinat
#

In [1]:
# Import the module
import numpy as np

In [14]:
# Create a matrix
matrix1 = np.array(range(1,37)).reshape((6,6))

In [16]:
# Print the result
print(matrix1)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [17]:
# Perform the calculations of determinant
determinant = np.linalg.det(matrix1)

In [19]:
# Print the result
print(f"Determinant of the matrix is: {determinant}")

Determinant of the matrix is: -1.5420311925294816e-61


In [ ]:
#
# Program 2: Verify, if the following pairs of vectors are perpendicular
#
# Input: variables: X1-X6
# Output: boolean: True or False
#
# Notes: Dot product of perpendicular vectors is zero.
# Define a function vectors_are_perpendicular(vect1, vect2), which will return True or False.
#

In [31]:
# Define function
def vectors_are_perpendicular(vect1, vect2):
    # Calculate the dot product of vect1 and vect2
    # Input : vect1, vect2
    # Output: True of False
    dot_product = sum(a * b for a,b in zip(vect1, vect2))
    
    # Check if the dot product equals zero
    if dot_product == 0:
        return True
    else:
        return False

In [26]:
# Variables:
X1 = [1, 1, 0] 
X2 = [ 2,-2, 0]

X3 = [1, 1, 0]
X4 = [-2,-2, 0]

X5 = [1, 1, 0]
X6 = [-2, 2, 0]

In [29]:
# Call the function
print(vectors_are_perpendicular(X1,X2))
print(vectors_are_perpendicular(X3,X4))
print(vectors_are_perpendicular(X5,X6))

True
False
True


In [32]:
#
# Program 3: Solve the system of linear equations
#
# Input: Matrix A and Y
# Output: Variables: x, y, z
#
# Notes: A @ X = Y, X = Ainv @ Y
#

In [ ]:
# Equations
# x + y + z = 6
# x - y + z = 2
# x + y - z = 0

In [33]:
# Matrix A
A = np.array([[1, 1, 1],
              [1, -1, 1],
              [1, 1, -1]])

In [36]:
# Matrix Y
Y = np.array([6, 2, 0])

In [37]:
# Calculate the inverse of matrix A
A_inv = np.linalg.inv(A)

In [38]:
# Solve for X
# @ symbol is used as the matrix multiplication operator
X = A_inv @ Y

In [39]:
# Print the result 
print(f"Solution:\nx = {X[0]}\ny = {X[1]}\nz = {X[2]}")

Solution:
x = 1.0
y = 2.0
z = 3.0


In [ ]:
#
# Program 4: Solve biquadratic equation: p*x**4 + r*x**2 + t = 0 for (p,r,t) = (1,-13,36) using NumPy
#
# Input: p,r,t
# Output: Roots of the biquadratic equation
#

In [3]:
# Input
p = 1
r = -13
t = 36

In [5]:
factor = [p, 0, r, 0, t] # the zeros are placeholders for the coefficients

In [6]:
# Calculations
roots = np.roots(factor)

In [7]:
# Print the result
print("Roots of the biquadratic equation:", roots)

Roots of the biquadratic equation: [-3. -2.  3.  2.]


In [ ]:
#
# Program 5: Conversion among degrees of Celsius, Kelvin, Farhenheit, and Reaumur using NumPy
#
# Input: c = temperature in [C]
# Output: k,f,r = temperature in Kelvin, Farhenheit, and Reaumur 
#
# Notes: no for-cycles
#

In [36]:
def conversion_of_temperature(c):
    # Conversion among degrees
    # Input: c = temperature in [C]
    # Output: k,f,r = temperature in Kelvin, Farhenheit, and Reaumur
    # Convert Celsius to Kelvin
    k = c + 273.15
    # Convert Celsius to Fahrenheit
    f = c * 9/5 + 32
    # Convert Celsius to Reaumur
    r = (c*4)/5
    return np.stack((c, k, f, r), axis=1)

In [37]:
# Input data
temperatures = np.array([-20, 0, 20, 40, 60, 80, 100])

In [38]:
# Call the function to convert the temperatures
converted_temperatures = conversion_of_temperature(temperatures)

In [42]:
# Print the table

In [48]:
print("C\tK\tF\tR")
print(converted_temperatures)

C	K	F	R
[[-20.   253.15  -4.   -16.  ]
 [  0.   273.15  32.     0.  ]
 [ 20.   293.15  68.    16.  ]
 [ 40.   313.15 104.    32.  ]
 [ 60.   333.15 140.    48.  ]
 [ 80.   353.15 176.    64.  ]
 [100.   373.15 212.    80.  ]]


In [49]:
#
# Program 6: Write program for matrix multiplication using NumPy
#
# Input: Matrix A and B
# Output: Multiplication of two matrices
#

In [54]:
# Input data
A = np.array([[1,2],
              [3,4]])
B = np.array([[5,6],
              [7,8]])

In [51]:
# Matrix multiplication
C = np.dot(A, B)

In [53]:
# Pritn the result
print(C)

[[19 22]
 [43 50]]
